version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: assignment-manager-app
    environment:
      DATABASE_URL: postgresql://postgres:123123@db:5432/assignment_manager
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  db:
    image: postgres:16
    container_name: assignment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: assignment_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d assignment_manager"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: