version: "3.9" 
services:
  assignment-db-test:
    image: postgres:16
    container_name: assignment-db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assignment_test
    ports:
      - "5433:5432"
    volumes:
      - assignment-manager_postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      retries: 10

  assignment-manager-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assignment-manager-test
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@assignment-db-test:5432/assignment_test?schema=public"
      NODE_ENV: test
    depends_on:
      assignment-db-test:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run test
      "

volumes:
  assignment-manager_postgres_data_test: