version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "51212:51212"
    container_name: assignment-manager-app
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
  db:
    image: postgres:16
    container_name: assignment-db

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d assignment_manager" ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  postgres_data:
